### PR TITLE
User interface

### PR DESCRIPTION
**Pull request by karthi07**
For the Tic Tac Toe project - Milestone 2

 we have implemented the following functions
- add_move
- init_cel_size
- puts_center
-printBoard

the code works well for the gameplay, game-winning logic will be added later

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, You are almost there my friend just few more things required. 
### General
- [x] Lets Fix stickler errors
* [x]  The Game should inform players if selected move is a winning move
* [x]  The Game should inform players if selected move is a draw move
- [x] Your loop needs to be terminated at some point , It can be done with variable rather than using 
 out-of-nowhere numbers to terminate a loop
```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move
  
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Good Job :clap: 
You have made quite a progress in this PR. However, we can't merge this one yet. We need to have a loop in this PR.
- [ ] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png)). A loop is required. This was already suggested by @kobiyoyo 
- [ ] fix the conflicts you have 

### Martin Afani

**Comment by karthi07** [comment]
@whiz25  @kobiyoyo   The Code has a valid loop to check the game flow. Its not "an out-of-nowhere numbers to terminate a loop" Please understand the valid game play has only 9 moves, that's why the while loop runs till 9. 

Please provide your comments.

**Comment by karthi07** [comment]
@whiz25  @kobiyoyo, do respond, I have raised two code review request and you decline for that.

 help me understands what wrong with the current logic. This contains a loop and logic work fine :thinking:

**Comment by whiz25** [comment]
@karthi07 I see your logic now. Please accept my apology. Re-send your code and I will approve it.

**Comment by karthi07** [comment]
> @karthi07 I see your logic now. Please accept my apology. Re-send your code and I will approve it.

Thanks a lot. sent for review :+1:

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work implementing the suggested changes :clap: However, you code needs a bit of refactoring in order to get approval for this milestone. Check :arrow_down: 

- [ ] Using out-of-nowhere numbers to terminate a loop, for example `5.times do ... end` is a signal that something is wrong. Advise usage of terminating variable like what the previous reviewer has requested.
- `while i < 9` is similar to `9.times`, the point is that you should make the loop only dependent on a terminating variable.

### That's it :relieved: When finished, kindly resubmit another code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by karthi07** [comment]
@stratospherique  I don't agree with this point. this is the format of the game, which has only 9 possible valid moves. Provide a better comment with logic before you request a change. be responsible, explain the real benefit of using a variable instead of this current loop.

### POINT OUT disadvantage of this method. THE GAME LOGIC IS BASED ON 9 VALID MOVES. 

That's what has been implemented.

**Comment by stratospherique** [comment]
> @stratospherique I don't agree with this point. this is the format of the game, which has only 9 possible valid moves. Provide a better comment with logic before you request a change. be responsible, explain the real benefit of using a variable instead of this current loop.
> 
> ### POINT OUT disadvantage of this method. THE GAME LOGIC IS BASED ON 9 VALID MOVES.
> That's what has been implemented.

### Okay, I understand your frustration. Thus, I am gonna give some reasons why we should use a loop terminating variable.

- The best code is the code that requires fewer changes whenever the requirements change. By that I mean, the developer should modify as less parts as possible of the code if the requirements change.

- For your case, imagine that the grid becomes 4x4 or 5x5, then you will need to modify the number of iterations that you assume that your game couldn't surpass. In addition, you will have to change all the logic related to input checking, winner/draw/continue conditions, etc. All of these modifications will impact various parts of the project. This implies that your code is un-maintainable and less extensible.

- The effect couldn't be easily seen in a small project like this, but our goal is to make students get used to applying coding best practices even in small projects because it will help them be better programmers in the future.

**Comment by karthi07** [comment]
@stratospherique I accept this point.

In the same case, This is Milestone 2, which only configures user interaction. for the cases of 4x4 and 5x5, I can add this in milestone 4. 

All over, this is not a requirement in either Micorverse Project spec or Odin project spec. This could be a valid suggestion to be added.

This review has been delaying our progress for no-point

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Hi Team,
## User interface looks amazing. Congratulation :+1: Approved.
Go ahead and merge to development.
_Goodluck in your next milestone_ *Happy coding*

**Comment by karthi07** [comment]
@kobiyoyo  @whiz25  @stratospherique Apologies for the long thread, my bad. we will be implementing the logic in the next Milestone 4  :+1:

**Pull request merged**
